# Generated by Django 3.2.20 on 2023-12-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20231219_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='s_login',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
